name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    
    - name: Run go vet
      run: go vet ./...
    
    - name: Run tests
      run: go test ./...
    
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest

	docker:
	    runs-on: ubuntu-latest
	    needs: test  # Only run if tests pass
	    
	    steps:
	    - uses: actions/checkout@v4
	    
	    - name: Set up Docker Buildx
	      uses: docker/setup-buildx-action@v3
	    
	    - name: Build Docker image
	      uses: docker/build-push-action@v5
	      with:
		context: .
		push: false  # Don't push to registry, just build
		tags: my-go-app:latest
	    
	    - name: Test Docker image
	      run: |
		docker run -d -p 8080:8080 --name test-app my-go-app:latest
		sleep 5
		curl -f http://localhost:8080/healthz || exit 1
		docker stop test-app
